### PR TITLE
Lefthand and sneaking fixes

### LINKED ISSUE #361: Left hand model isnt rendered on server
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Arch

### Server Software Version/Commit

latest

### What happened?

The left hand model does not render on the server instead right hand model is present

### To Reproduce

1.Go to settings
2.Skin Customization
3.Select left hand model

### Expected behavior

its expected for a left hand to be rendered and to appear rather then right hand.

### PR DESCRIPTION
**Pull request by Alvsch**
## Description
* Fixes #361 
* Fixed sneaking not working

## Testing
* Sneaking in-front of other players work.
* Switching between left and right handed is shown on the client.
* Hit animation swings with right arm for both self and others.

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings: `cargo clippy`
- [x] All unit tests pass: `cargo test`

### CODE REVIEW

File: pumpkin/src/client/player_packet.rs [hunk 1]
```diff
@@ -442,6 +449,7 @@ impl Player {
                 text_filtering: client_information.text_filtering,
                 server_listing: client_information.server_listing,
             };
+            self.update_client_information().await;
```
Comment (Snowiiii) [inline pumpkin/src/client/player_packet.rs:452]: why here

Comment (Alvsch) [reply pumpkin/src/client/player_packet.rs:452]: - - This is where we receive the new client information from the player, like skin layers and which hand they are using. So the function is called every time we get new information

**Comment by Snowiiii** [comment]
Looks good.
Thanks @Alvsch
