### PR TITLE
Use sysinfo, this will fix #311

### LINKED ISSUE #311: Unable to compile in Termux since `sys-info` lib was added
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Termux 0.119.0-beta1, Android 14

### Server Software Version/Commit

a23ce773ad170a6507e79c4aab43693783ec58ae

### What happened?

Since [that exact commit](https://github.com/Snowiiii/Pumpkin/commit/e4190459edad91f0f5e82c05520d7f0871f555b2) it became impossible to build Pumpkin. It is a [known issue](https://github.com/FillZpp/sys-info-rs/issues/116) and I'm getting the exact same error message.

### To Reproduce

Download and install Termux from F-Droid, update packages, install cargo and git, clone repo and try `cargo build`.

### Expected behavior

To be able to compile and run Pumpkin in Termux without issues.

### PR DESCRIPTION
**Pull request by Commandcracker**
## Description
sysinfo is actively developed, supports android and will default no null values if the OS is not detected.
(See https://github.com/Snowiiii/Pumpkin/issues/311#issuecomment-2483096761)
            

## Testing
Ran on Win11 and linux (wls docker) and android (Samsung tabled)

Windows
Screenshot 2024-11-18 203025
Android
image
Docker
Screenshot 2024-11-18 204723

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings `cargo clippy`

### CODE REVIEW

File: pumpkin/src/main.rs [hunk 1]
```diff
@@ -95,38 +96,85 @@ const fn convert_logger_filter(level: pumpkin_config::logging::LevelFilter) -> L
...
-                arch
+                "CPU Information: Brand: \"{}\", Frequency: {} GHz, Physical Cores: {}, Logical Processors: {}",
+                cpu.brand(),
+                cpu.frequency() / 1000,
+                sys.physical_core_count().unwrap_or(0),
+                cpus.len()
             );
-            return;
+        } else {
+            log::info!("CPU Information: Could not retrieve CPU details.");
```
Comment (Commandcracker) [inline pumpkin/src/main.rs:145]: should this be log::warn! ?

Comment (neeleshpoli) [reply pumpkin/src/main.rs:145]: Yeah I think warning is better

**Comment by Snowiiii** [comment]
LGTM.
Thanks @Commandcracker
