### PR TITLE
fix: copper chests and wooden shelves facing wrong direction

### LINKED ISSUE #1318: Copper Chest Always Facing North
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

WIndows

### Server Software Version/Commit

Pumpkin 0.1.0-dev+1.21.11

### What happened?

when you place a Copper Chest it always faces north automatically even when placed south east or west

### To Reproduce

place any type of copper chest

### Expected behavior

it should be placing in the direction you placed it at

### LINKED ISSUE #1321: Shelves placing wrong direction leading to them being mid-air
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

Windows

### Server Software Version/Commit

Pumpkin 0.1.0-dev+1.21.11

### What happened?

When you place one of the new "Shelves" it always places sideways so for example lets say my blocks are placed north side and the shelfis placed facing south so its not placed on my block its placed mid air 

### To Reproduce

places a shelf and see

### Expected behavior

it should stay on the blocks and not rotate to the side where no blocks are

### PR DESCRIPTION
**Pull request by Purdze**
## Summary
- add copper chest block IDs to ChestBlock handler so they use proper facing logic
- create new ShelfBlock handler for wooden shelf blocks (oak_shelf, bamboo_shelf, etc.)
- fix `get_horizontal_facing()` to use vanilla's formula: `floor(yaw / 90.0 + 0.5) & 3`
- use runtime block ID lookup instead of compile-time macro to avoid ID mismatch

fixes #1318
fixes #1321

### CODE REVIEW

File: pumpkin/src/block/blocks/chiseled_bookshelf.rs [hunk 1]
```diff
@@ -16,17 +16,23 @@ use pumpkin_data::{
...
+use crate::block::BlockMetadata;
+
 pub struct ChiseledBookshelfBlock;
 
+impl BlockMetadata for ChiseledBookshelfBlock {
+    fn ids() -> Box<[u16]> {
+        [pumpkin_data::Block::CHISELED_BOOKSHELF.id].into()
+    }
+}
+
```
Comment (CuzImClicks) [inline pumpkin/src/block/blocks/chiseled_bookshelf.rs]: why did you manually implement the exact code the macro generates?

```rust
pub struct ChiseledBookshelfBlock;

impl crate::block::BlockMetadata for ChiseledBookshelfBlock {
    fn ids() -> Box<[u16]> {
        [178u16].into()
    }
}
```

File: pumpkin/src/block/blocks/shelf.rs [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+    tag,
+};
+use pumpkin_world::BlockStateId;
+
+use crate::block::{BlockBehaviour, BlockFuture, BlockMetadata, OnPlaceArgs};
+use crate::entity::EntityBase;
+
+pub struct ShelfBlock;
+
+impl BlockMetadata for ShelfBlock {
```
Comment (CuzImClicks) [inline pumpkin/src/block/blocks/shelf.rs]: `#[pumpkin_block_from_tag("minecraft:fence_gates")]`

File: pumpkin/src/block/blocks/chests.rs [hunk 3]
```diff
@@ -68,7 +68,12 @@ pub struct ChestBlock;
 
 impl BlockMetadata for ChestBlock {
```
Comment (CuzImClicks) [inline pumpkin/src/block/blocks/chests.rs]: i dont think you can merge copper chests and normal chests... because copper chests also need to handle the copper behaviors.

File: pumpkin/src/block/blocks/chiseled_bookshelf.rs (hunk 1 above)
Comment (Purdze) [reply pumpkin/src/block/blocks/chiseled_bookshelf.rs]: was testing some things, was an oversight, fixed

**Comment by Purdze** [comment]
> left you some comments for improvements

thank you :D

File: pumpkin/src/lib.rs [hunk 4]
```diff
@@ -205,34 +206,33 @@ impl PumpkinServer {
             });
         }
 
-        let mut tcp_listener = None;
-
-        if server.basic_config.java_edition {
+        let tcp_listener = if server.basic_config.java_edition {
             let address = server.basic_config.java_edition_address;
```
Comment (Snowiiii) [inline pumpkin/src/lib.rs:207]: Please revert

**Comment by Snowiiii** [comment]
@Purdze the tcp_listener listener code is still modified

File: pumpkin/src/lib.rs [hunk 5]
```diff
@@ -178,8 +178,6 @@ impl PumpkinServer {
 
         let rcon = server.advanced_config.networking.rcon.clone();
 
-        let mut ticker = Ticker::new();
```
Comment (Snowiiii) [inline pumpkin/src/lib.rs]: I also actually just saw this is also already fixed on master

**Comment by Snowiiii** [comment]
Looks good. Thank you @Purdze :D
