### PR TITLE
fix: jukebox now properly handles music discs

### LINKED ISSUE #568: Jukebox does not drop used discs
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

CachyOS

### Server Software Version/Commit

Pumpkin 0.1.0-dev (3f1fd5a)

### What happened?

I played a disc on the jukebox, music plays without problem, but when you try to get the disk back by right-clicking the jukebox, the music stops but the disc does not get returned to the player. Also the disc is not removed from player inventory when inserted on the jukebox on survival

### To Reproduce

- Grab a disc
- Put the disc on the jukebox
- Try to get it back

### Expected behavior

- Put disc on the jukebox
- Disc gets removed from player inventory and is inserted on the jukebox
- Music plays
- Right click the jukebox
- Music stops
- Disc is dropped from the jukebox

### PR DESCRIPTION
**Pull request by Purdze**
## summary
- add `JukeboxBlockEntity` for disc storage and playback tracking
- disc is removed from player inventory when inserted (respects creative mode)
- disc drops when player right-clicks jukebox to retrieve it
- disc drops when jukebox is broken
- redstone power output (15 when playing, 0 otherwise)
- comparator output varies per song (vanilla values 1-15)
- playback auto-stops when song finishes

fixes #568

### CODE REVIEW

File: pumpkin-data/build/jukebox_song.rs [hunk 1]
```diff
@@ -54,6 +54,78 @@ pub(crate) fn build() -> TokenStream {
         })
         .collect::<TokenStream>();
 
+    // Vanilla song durations in seconds from JukeboxSongs.java
+    let song_lengths: BTreeMap<&str, u32> = [
```
Comment (Snowiiii) [inline pumpkin-data/build/jukebox_song.rs]: Please don't hardcode such things, instead we use the extractor

File: pumpkin-data/build/jukebox_song.rs [hunk 2]
```diff
@@ -1,18 +1,40 @@
...
+    length_in_seconds: f32,
+    comparator_output: u8,
+}
+
 pub(crate) fn build() -> TokenStream {
     println!("cargo:rerun-if-changed=../assets/jukebox_song.json");
+    println!("cargo:rerun-if-changed=../assets/registry/1_21_11_synced_registries.json");
 
-    let songs: BTreeMap<String, u32> = serde_json::from_str(
+    let songs: IndexMap<String, u32> = serde_json::from_str(
```
Comment (Snowiiii) [inline pumpkin-data/build/jukebox_song.rs]: look at Clippy.toml

**Comment by Snowiiii** [comment]
LGTM. Thank you @Purdze :D
