### PR TITLE
fix: eggs, snowballs, and babies

### LINKED ISSUE #567: Projectiles do not break
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

CachyOS

### Server Software Version/Commit

3f1fd5a

### What happened?

I threw a snowball, and when it hit a block, it did not break, i threw an egg too, same behavior. Also is limited to a diagonal on the x-z axis, and when you re-connect projectiles launch from where they we're launched again

### To Reproduce

- Get a throwable projectile, like an snowball
- Shoot it aiming to a block

### Expected behavior

The projectile must do it's thing (Spawning a chicken, do damage, tp, etc) and then break itself/disappear

### LINKED ISSUE #1332: When throwing eggs or snowballs as soon as they hit a block they are hanging in them and then despawn after some seconds
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

Windows

### Server Software Version/Commit

Pumpkin 0.1.0-dev+1.21.11

### What happened?

When throwing eggs or snowballs as soon as they hit a block they are hanging in them and then despawn after some seconds

and the new copper egg / blue egg you cant even throw them

### To Reproduce

throw an Egg / Snow ball

### Expected behavior

it should like show the vanilla egg / Snowball animation

### PR DESCRIPTION
**Pull request by RoosterBooster007**
## Description
- Thrown eggs (including blue and brown) and snowballs behave as expected now (they hit/clear)
- Eggs now have a chance at spawning (multiple) baby chickens 🍗
   - You can now set entity age before spawning (for babies)
- Snowballs damage blazes

## Testing
However, the chickens are all temperate/default as entity variants need to be implemented
Sounds and particles work (but could be tweaked later)
Also, velocity and drag values could be updated (projectiles seem fast atm)

Wind charges, epearls, arrows, and firework colors are next...

Fixed #567
Fixed #1332

### CODE REVIEW

File: pumpkin/src/entity/projectile/egg.rs [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+use pumpkin_protocol::codec::item_stack_seralizer::ItemStackSerializer;
+use pumpkin_protocol::java::client::play::Metadata;
+use pumpkin_util::math::vector3::Vector3;
+use pumpkin_world::item::ItemStack;
+use tokio::sync::Mutex;
+use uuid::Uuid;
+
+pub struct EggEntity {
+    pub thrown: ThrownItemEntity,
+    pub item_stack: Mutex<ItemStack>,
```
Comment (CuzImClicks) [inline pumpkin/src/entity/projectile/egg.rs]: Just for my understanding… why do we need to store the itemstack behind a mutex when we know that the itemstack (when initialized via new()) can and probably should only ever be a single egg?

File: pumpkin/src/entity/projectile/egg.rs [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+            let r: u8 = rand::random(); // 0..=255
+            let to_spawn = if r == 0 {
+                4
+            } else if r < 32 {
+                1
+            } else {
+                0
+            };
+
+            // Spawn chickens in a separate task to prevent stack overflow
```
Comment (CuzImClicks) [inline pumpkin/src/entity/projectile/egg.rs:128]: How does spawning 1 or 4 entities cause a stack overflow?

File: pumpkin/src/entity/projectile/egg.rs (hunk 1 above)
Comment (RoosterBooster007) [reply pumpkin/src/entity/projectile/egg.rs]: Nice catch, we don't. I'll update this to read or clone when I get back to my PC.

File: pumpkin/src/entity/projectile/egg.rs (hunk 2 above)
Comment (RoosterBooster007) [reply pumpkin/src/entity/projectile/egg.rs:128]: Something strange was happening when spawning multiple chickens in one tick, but now I think it's due to a projectile collision loop. I can try to fix this by using a simple ``has_hit`` boolean flag to stop the overflow, instead.

**Comment by RoosterBooster007** [comment]
@Snowiiii, I finally fixed the clippy errors

File: pumpkin/src/entity/mod.rs [hunk 3]
```diff
@@ -189,6 +204,16 @@ pub trait EntityBase: Send + Sync + NBTStorage {
         Box::pin(async {})
     }
 
+    fn on_hit(&self, _hit: crate::entity::projectile::ProjectileHit) -> EntityBaseFuture<'_, ()> {
+        Box::pin(async {})
+    }
+
+    /// Returns true if this entity is a projectile (egg, snowball, etc.).
+    /// Default is false.
+    fn is_projectile(&self) -> bool {
```
Comment (Snowiiii) [inline pumpkin/src/entity/mod.rs]: This seems kinda unnecessary, i think instead we may should just check the type

**Comment by RoosterBooster007** [comment]
@Snowiiii does this look okay now?

**Comment by Snowiiii** [comment]
Overall looks fine. Thank you @RoosterBooster007 :D
