### PR TITLE
fix: use command sender dimension when tp

### LINKED ISSUE #1678: /tp Moves player to the overworld
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

Arch Linux

### Server Software Version/Commit

33cb7e5

### What happened?

When you run the /tp command with angle arguments, you get moved to the overworld. 

### To Reproduce

1. Go to the nether (beware of #1673
2. Run a teleport command with angle arguments (such as `/tp @s 0 90 0 -164.36 24.45`)
3. Observe that you are now in the overworld

### Expected behavior

/tp should always preserve the dimension you are in. Note that this doesn't occur when you don't have the angle arguments.

### PR DESCRIPTION
**Pull request by chocodev11**
Fixes #1678 

## Testing

Please follow our [Coding Guidelines](https://github.com/Pumpkin-MC/Pumpkin/blob/master/CONTRIBUTING.md#coding-guidelines)

### CODE REVIEW

**Review by topi-banana — APPROVED** [review]

File: pumpkin/src/command/commands/teleport.rs [hunk 1]
```diff
@@ -193,12 +193,11 @@ impl CommandExecutor for EntitiesToPosWithRotationExecutor {
             // For teleport, we use absolute values only (ignore relative flags)
             let (yaw, _, pitch, _) = RotationArgumentConsumer::find_arg(args, ARG_ROTATION)?;
 
-            // todo command context
-            let world = server.worlds.load().first().unwrap().clone();
             for target in targets {
+                let world = target.get_entity().world.load_full();
```
Comment (RoosterBooster007) [inline pumpkin/src/command/commands/teleport.rs]: This appears to work, but it breaks teleportations under certain circumstances. If a player in the nether tries to teleport a player (who's in the overworld), they will be teleported in the overworld and not to the player in the nether. Basically, the dimension the command was executed from matters.

Try something like this instead:
```rust
// Resolve world based on command sender context
let world = match sender {
    CommandSender::Rcon(_) | CommandSender::Console | CommandSender::Dummy => {
        server.worlds.load().first().unwrap().clone()
    }
    CommandSender::Player(player) => player.world().clone(),
    CommandSender::CommandBlock(_, w) => w.clone(),
};
```

**Review by RoosterBooster007 — APPROVED** [review]

File: pumpkin/src/command/commands/teleport.rs [hunk 2]
```diff
@@ -109,14 +118,7 @@ impl CommandExecutor for EntitiesToPosFacingPosExecutor {
...
             let (yaw, pitch) = yaw_pitch_facing_position(&pos, &facing_pos);
-            //todo
-            let world = match sender {
-                CommandSender::Rcon(_) | CommandSender::Console | CommandSender::Dummy => {
-                    server.worlds.load().first().unwrap().clone()
-                }
-                CommandSender::Player(player) => player.world().clone(),
-                CommandSender::CommandBlock(_, w) => w.clone(),
-            };
+            let world = resolve_sender_world(sender, server);
```
Comment (RoosterBooster007) [inline pumpkin/src/command/commands/teleport.rs:121]: When teleporting to another entity/player, can you actually have it set the pos/world to the destination entity's? That way, teleportation works like in vanilla.

**Comment by RoosterBooster007** [comment]
Thanks, @chocodev11! 📍
