### PR TITLE
Read static instead of dynamic

### LINKED ISSUE #1113: Error occurred while starting Docker
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

windows

### Server Software Version/Commit

sha-9f94ce1

### What happened?

Docker startup shows no data file: Os { code: 2, kind: NotFound, message: "No such file or directory" }

Image

### To Reproduce

Start the Docker server

### Expected behavior

Normal operation

### PR DESCRIPTION
**Pull request by Commandcracker**
## Description
Resolves #1113

## Testing

Please follow our [Coding Guidelines](https://github.com/Pumpkin-MC/Pumpkin/blob/master/CONTRIBUTING.md#coding-guidelines)

### CODE REVIEW

File: pumpkin-util/src/lib.rs [hunk 1]
```diff
@@ -44,6 +44,7 @@ macro_rules! global_path {
     }};
 }
 
+/// Reads JSON files form disk. Don't use this for static files!
```
Comment (teknostom) [inline pumpkin-util/src/lib.rs]: form -> from?

Comment (Commandcracker) [reply pumpkin-util/src/lib.rs]: omg i cant type

**Comment by Snowiiii** [comment]
LGTM. Thank you @Commandcracker :D 🐐
