### PR TITLE
fix: placing blocks on composters

### LINKED ISSUE #942: Placing blocks on Composter's
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

Windows 11

### Server Software Version/Commit

Pumpkin 0.1.0-dev+1.21.6 (fe5ab68)

### What happened?

In vanilla you can place blocks on a composter without sneaking, but you cant do it on Pumpkin.

### To Reproduce

Try to place a block on a Composter (without sneaking).

### Expected behavior

The blocks to be palced.

### PR DESCRIPTION
**Pull request by RoosterBooster007**
## Description
This fix addresses the composter block placement bug, allowing players to now place blocks properly next to composters (without sneaking).

## Testing
You can now place blocks off of composters without the interaction and block being consumed (see attached image).
Screenshot 2026-01-22 153448

Fixes #942

### CODE REVIEW

File: pumpkin/src/block/blocks/composter.rs [hunk 1]
```diff
@@ -50,24 +50,42 @@ impl BlockBehaviour for ComposterBlock {
...
+                    args.world
+                        .sync_world_event(WorldEvent::ComposterUsed, *args.position, 1)
+                        .await;
+                    true
+                } else {
+                    false
+                }
+            };
+
+            if handled {
```
Comment (Snowiiii) [inline pumpkin/src/block/blocks/composter.rs]: I think instead of defining handled it would be better to just early return `BlockActionResult::Consume` or ` BlockActionResult::Pass`

Comment (RoosterBooster007) [reply pumpkin/src/block/blocks/composter.rs]: Agreed, that's cleaner. I also made it so that items are now consumed if that's alright.

**Comment by Snowiiii** [comment]
Looks good. Thank you @RoosterBooster007 :D
