### PR TITLE
fix: collision

### LINKED ISSUE #1505: touching cactus doesnt deal damage
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

windows 11

### Server Software Version/Commit

0.1.0-dev+1.21.11

### What happened?

when touching a cactus it doesnt deal damage

### To Reproduce

touch a cactus

### Expected behavior

Deal damage

### PR DESCRIPTION
**Pull request by JustMarfix**
## Description

This fixes collision logic for cactus, campfire and probably some other blocks.

Fixes #1505

### CODE REVIEW

File: pumpkin-data/src/block_state.rs [hunk 1]
```diff
@@ -89,6 +89,12 @@ impl BlockState {
         self.state_flags & IS_SOLID != 0
     }
 
+    pub const fn block_movement(&self) -> bool {
+        self.id != 129 && // cobweb
```
Comment (FMMazur) [inline pumpkin-data/src/block_state.rs]: i think it would be better:
```rs
pub const fn block_movement(&self) -> bool {
        self.id != Block::COBWEB.id &&
        self.id != Block::BAMBOO_SAPLING.id &&
        self.is_solid()
    }
```

Comment (Purdze) [reply pumpkin-data/src/block_state.rs]: there's already blocks_movement() in block_properties that does this same check, so neither the hardcoded IDs nor the Block::COBWEB.id version are needed, just use the existing function

Comment (JustMarfix) [reply pumpkin-data/src/block_state.rs]: yeah, already figured it out, I somehow missed it lol
thx for comments

**Comment by JustMarfix** [comment]
> Hardcoded state IDs (129, 789) will break on registry changes, use block constants instead. Also, removing the -0.001 bbox shrink and using a full-block AABB instead of actual collision shapes will cause false-positive collisions at block edges.

I brought back box shrink, yet made it 1.0E-5F as in vanilla code.

It also turns out vanilla uses `VoxelShapes.fullCube()` as the result of `getInsideCollisionShape(...)` for almost all blocks, except for powder snow, cauldron with lava and water, tripwire and end portal block. So I made a new function in BlockBehaviour to overwrite default behaviour if needed.

**Comment by JustMarfix** [comment]
> self.health.store(self.health.load() - amount) in item damage is a race condition with concurrent damage sources, needs an atomic read-modify-write and the bbox shrink epsilon is 1.0E-5 but vanilla uses 1.0E-7

Done. Also implemented atomicf32, as discussed [here](https://discord.com/channels/1268592337445978193/1268611318617866261/1471242409139634456).

**Comment by Purdze** [comment]
Looks good thank you
