### PR TITLE
fix: implement powder snow freeze effect and damage

### LINKED ISSUE #795: Getting frozen makes you stay frozen forever
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

Linux

### Server Software Version/Commit

Pumpkin 0.1.0-dev+1.21.5 (bfc2f679)

### What happened?

When you walk into snow, you get frozen, but when you walk out, you stay frozen, forever.

### To Reproduce

Place a snow block, then walk through it. 

### Expected behavior

You will be cold forever

### PR DESCRIPTION
**Pull request by Purdze**
## Summary
- add `frozen_ticks` field to track freeze duration
- send `DATA_FROZEN_TICKS` metadata to clients for visual freeze effect
- freeze ticks increase by 1/tick in powder snow, decrease by 2/tick outside
- deal 1 freeze damage every 40 ticks when fully frozen (140 ticks)
- add freeze immunity for snow golems, strays, polar bears, wither, wither skeletons

Fixes #795

### CODE REVIEW

File: pumpkin/src/entity/mod.rs [hunk 1]
```diff
@@ -1552,6 +1556,68 @@ impl Entity {
...
+    /// Check if the entity is currently in powder snow
+    pub async fn is_in_powder_snow(&self) -> bool {
+        let block_pos = self.block_pos.load();
+        self.world.load().get_block(&block_pos).await == &Block::POWDER_SNOW
+    }
+
+    /// Check if this entity type is immune to freezing
+    /// In vanilla: snow golems, strays, polar bears, wither, wither skeletons
+    pub fn is_freeze_immune(&self) -> bool {
+        std::ptr::eq(self.entity_type, &EntityType::SNOW_GOLEM)
```
Comment (Snowiiii) [inline pumpkin/src/entity/mod.rs]: The tag FREEZE_IMMUNE_ENTITY_TYPES should be used here

File: pumpkin/src/entity/mod.rs [hunk 2]
```diff
@@ -1578,6 +1583,66 @@ impl Entity {
...
+    pub async fn is_in_powder_snow(&self) -> bool {
+        let block_pos = self.block_pos.load();
+        self.world.load().get_block(&block_pos).await == &Block::POWDER_SNOW
+    }
+
+    /// Check if this entity type is immune to freezing
+    /// Uses the `minecraft:freeze_immune_entity_types` tag
+    pub fn is_freeze_immune(&self) -> bool {
+        self.entity_type
+            .is_tagged_with("minecraft:freeze_immune_entity_types")
```
Comment (Snowiiii) [inline pumpkin/src/entity/mod.rs]: instead of this you should use `.has_tag(&tag::EntityType::MINECRAFT_FREEZE_IMMUNE_ENTITY_TYPES)`

**Comment by Snowiiii** [comment]
Looks good now. Thank you @Purdze :D
