### PR TITLE
fix: align player pose resolution with vanilla to prevent crawl in-wall damage

### LINKED ISSUE #1315: Crawling under a block damages the player
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

Arch Linux

### Server Software Version/Commit

0.1.0/6f18d165

### What happened?

When you get into crawl/swim/elytra fly mode and are underneath a block, you start taking damage as if you were suffocating.

### To Reproduce

1. put some blocks on the surface of the ocean
2. go into survival mode
3. swim underneath said blocks

### Expected behavior

Don't take damage because your hitbox isn't in a block

### PR DESCRIPTION
**Pull request by aShanki**
## Summary
- fix player pose selection to better mirror vanilla pose resolution rules
- update pose on Java movement/sneak/elytra transitions so hitbox metadata matches state changes
- run pose reconciliation each player tick to match vanilla tick behavior
- keep Bedrock unchanged in this PR as requested

## Why
Issue #1315 reports players taking `in_wall` damage while crawling/swimming under blocks. The root cause is stale/incorrect pose selection, which keeps a too-tall hitbox in constrained spaces.

## Parity notes
Compared against vanilla 1.21.11 `Player.updatePlayerPose()` behavior:
- spectator/passenger can keep desired pose
- crouching is suppressed while ability-flying
- pose is updated every tick

Closes #1315

### CODE REVIEW

File: pumpkin/src/net/java/play.rs [hunk 1]
```diff
@@ -300,6 +300,7 @@ impl JavaClient {
                 let entity = &player.living_entity.entity;
                 let last_pos = entity.pos.load();
                 player.living_entity.entity.set_pos(pos);
+                player.update_player_pose().await;
```
Comment (BjornTheProgrammer) [inline pumpkin/src/net/java/play.rs]: We should probably handle this in Bedrock as well. Are you able to confirm this is an issue in Bedrock, and if so would you be able to update the bedrock code as well? If not we can implement it in the future.

Comment (aShanki) [reply pumpkin/src/net/java/play.rs]: I do have bedrock but I'd rather make that a seperate PR if possible

Comment (BjornTheProgrammer) [reply pumpkin/src/net/java/play.rs]: Alright, I'll test this PR and see if Purdze is able to merge

**Review by BjornTheProgrammer — APPROVED** [review]

**Comment by Purdze** [comment]
- Missing isSwimming() check — vanilla returns EntityPose.SWIMMING when the player is sprint-swimming in water; this never proactively enters the swimming pose
- Missing isUsingRiptide() / SPIN_ATTACK pose in the priority chain
- Sleeping check reads current_pose == Sleeping instead of a state flag — vanilla uses isSleeping() (checks sleepingPosition.isPresent()), not the current pose
- update_player_pose() is called from 5 packet handlers — vanilla only calls updatePose() once per tick from
PlayerEntity.tick(); the extra calls cause redundant async block lookups, potential race conditions, and double
metadata broadcasts
- Tick ordering is inverted — vanilla runs super.tick() (updates swimming/fluid state) before updatePose(), but this
PR calls update_player_pose() before living_entity.tick()
- The special-case crawl branch (current_pose == Swimming && !can_fit(Standing)) doesn't exist in vanilla — vanilla
handles crawling through its fallback chain (desired → crouching → swimming) which already covers this
- set_sneaking() unconditionally sets the pose to Crouching/Standing — vanilla's setSneaking() only sets the flag and
lets updatePose() handle pose resolution

If things cant be done yet, put a TODO
